### ISSUE TITLE
 Cannot read property 'toString' of undefined: 

### ISSUE THREAD

**Issue by mjbvz** [evilz/vscode-reveal#16]
I'm seeing this error while saving files (usually my settings):

```
shell.ts:419 [evilz.vscode-reveal] Cannot read property 'toString' of undefined: TypeError: Cannot read property 'toString' of undefined
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:345115
	at e.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:55287)
	at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:57078)
	at BrowserContentProvider.update (/Users/matb/.vscode-insiders/extensions/evilz.vscode-reveal-0.0.9/out/src/BrowserContentProvider.js:23:27)
	at context.subscriptions.push.vscode.workspace.onDidSaveTextDocument (/Users/matb/.vscode-insiders/extensions/evilz.vscode-reveal-0.0.9/out/src/extension.js:80:22)
	at e.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:55287)
	at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:57078)
	at e.$acceptModelSaved (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:347983)
	at t.e.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:423343)
	at e._invokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:279983)
```

I'll submit a PR with a fix

**Comment by evilz** [comment]
Thank for this PR man ! 

I just understand the bug. nice shot ;p
Maybe I should check the server state too.
