### ISSUE TITLE
Bad refresh on onDidChangeActiveTextEditor

### ISSUE THREAD

**Issue by evilz** [evilz/vscode-reveal#29]
mainThreadExtensionService.ts:44 TypeError: Cannot read property 'refresh' of undefined
    at refreshAll (C:\Users\Riges\.vscode\extensions\evilz.vscode-reveal-2.0.2\out\src\extension.js:31:30)
    at vscode.window.onDidChangeActiveTextEditor.editor (C:\Users\Riges\.vscode\extensions\evilz.vscode-reveal-2.0.2\out\src\extension.js:54:13)
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:87:238)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:485:858
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:87:218)
    at e.$acceptDocumentsAndEditorsDelta (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:435:723)
    at t.e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:516:87)
    at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:357:580)
    at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:357:270)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:356:206
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:358:204
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:85:988
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:87:218)
    at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:135:717)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream
mainThreadExtensionService.ts:43 [evilz.vscode-reveal]Cannot read property 'refresh' of undefined
e.$onExtensionRuntimeError    @    mainThreadExtensionService.ts:43
e.invoke    @    abstractThreadService.ts:42
e._invokeHandler    @    rpcProtocol.ts:109
e._receiveOneMessage    @    rpcProtocol.ts:96
(anonymous)    @    rpcProtocol.ts:32
(anonymous)    @    rpcProtocol.ts:157
e.fire    @    event.ts:142
(anonymous)    @    ipc.net.ts:81
emitOne    @    events.js:96
emit    @    events.js:191
readableAddChunk    @    _stream_readable.js:178
Readable.push    @    _stream_readable.js:136
onread    @    net.js:560

**Comment by evilz** [comment]
Should be resolve in V3
