### ISSUE TITLE
Export to HTML crash

### ISSUE THREAD

**Issue by delepster** [evilz/vscode-reveal#686]
I use VS Code 1.57.0 on Windows 10 and version 4.0.3 of the extension.

When I try to export my deck to HTML, it crashes with the following:
```pswh
[2021-06-14 16:26:55.023] [exthost] [error] Error: Webview is disposed
	at h.assertNotDisposed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:56898)
	at h.set html [as html] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:56080)
	at le.refreshWebView (c:\Users\glepine\.vscode\extensions\evilz.vscode-reveal-4.0.3\dist\extension.js:185:120373)
	at export (c:\Users\glepine\.vscode\extensions\evilz.vscode-reveal-4.0.3\dist\extension.js:185:117802)
	at async c:\Users\glepine\.vscode\extensions\evilz.vscode-reveal-4.0.3\dist\extension.js:185:108752
	at async _executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:108086) vscode-revealjs.exportHTML
```

**Comment by evilz** [comment]
Fixed in 4.1.0
