### ISSUE TITLE
Running the contributed command: 'vscode-revealjs.showRevealJSInBrowser' failed.

### ISSUE THREAD

**Issue by xiaomaimuchanyiyiba** [evilz/vscode-reveal#708]
![image](https://user-images.githubusercontent.com/28698753/130387159-91113a91-a9e6-46d6-b8db-c51855c2e348.png)
![image](https://user-images.githubusercontent.com/28698753/130387216-9dfdf762-2cac-4856-aeae-657ac1c10c49.png)
error reported when i click the button or run command on command board, but without any error log on the output window
---
Version: 1.59.1 (user setup)
commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
date: 2021-08-19T11:56:46.957Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by xiaomaimuchanyiyiba** [comment]
[2021-08-23 11:55:39.906] [exthost] [error] Error: No browser found
	at c:\Users\liumingyuan01\.vscode\extensions\tokiedokie.reveal-markdown-2.0.1\dist\extension.js:202:163956
	at _executeContributedCommand (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:109251)
	at _.$executeContributedCommand (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:109689)
	at h._doInvokeHandler (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12819)
	at h._invokeHandler (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12503)
	at h._receiveRequest (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:11159)
	at h._receiveOneMessage (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:9943)
	at c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:8039
	at d.fire (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
	at c.fire (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)
	at c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:30060
	at d.fire (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
	at c.fire (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)
	at r._receiveMessage (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:21091)
	at c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17969
	at d.fire (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
	at v.acceptChunk (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:13186)
	at c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12534
	at Socket.w (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:13218)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) vscode-revealjs.showRevealJSInBrowser

**Comment by xiaomaimuchanyiyiba** [comment]
> [2021-08-23 11:55:39.906] [exthost] [error] Error: No browser found
> at c:\Users\liumingyuan01.vscode\extensions\tokiedokie.reveal-markdown-2.0.1\dist\extension.js:202:163956
> at _executeContributedCommand (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:109251)
> at _.$executeContributedCommand (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:109689)
> at h._doInvokeHandler (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12819)
> at h._invokeHandler (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12503)
> at h._receiveRequest (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:11159)
> at h._receiveOneMessage (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:9943)
> at c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:8039
> at d.fire (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
> at c.fire (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)
> at c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:30060
> at d.fire (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
> at c.fire (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)
> at r._receiveMessage (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:21091)
> at c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17969
> at d.fire (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
> at v.acceptChunk (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:13186)
> at c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12534
> at Socket.w (c:\Users\liumingyuan01\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:13218)
> at Socket.emit (events.js:315:20)
> at addChunk (internal/streams/readable.js:309:12)
> at readableAddChunk (internal/streams/readable.js:284:9)
> at Socket.Readable.push (internal/streams/readable.js:223:10)
> at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) vscode-revealjs.showRevealJSInBrowser

I am using MicroSoft Edge Browser. When I installed a Chrome Browser, this extension will open Chrome and it works well
